# Generated by Django 5.1.6 on 2025-02-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_tasks_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
