# Generated by Django 5.1.6 on 2025-02-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_tasks_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='completed',
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
